apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        chart: {{ template "fullname" . }}
        tier: app
    spec:
      imagePullSecrets:
        - name: acr-auth2
        initContainers:
        - name: keyvault-agent
          image: {{ .Values.imgrepo }}vault-agent:1
          env:
          - name: VAULT_BASE_URL
            value: https://{{ .Values.vaultname }}-vault.vault.azure.net/
          - name: SERVICE_PRINCIPLE_FILE_PATH
            value: /host/azure.json
          - name: SECRETS_FOLDER
            value: /vault
          - name: SECRETS_KEYS
            value: insightskey
          volumeMounts:
          - name: vault
            mountPath: /vault
          - name: host-sp
            mountPath: /host/azure.json
            readOnly: true
      containers:
        - name: react-pwa
          image: "{{ .Values.imgrepo }}{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              export APPINSIGHTS_INSTRUMENTATIONKEY=$(cat /etc/vault/secrets/insightskey)
              yarn start
          ports:
          - containerPort: {{ .Values.app.internalPort}}
          env:
          - name  : NODE_ENV
            value : production
          volumeMounts:
          - mountPath: /etc/vault
            name: vault
            readOnly: true
      volumes:
        - name: vault
          emptyDir:
            # we want the secrets to reside only in-memory
            medium: Memory
        - name: host-sp
          hostPath:
            # this file contains the cluster service-principal, it exists on every node by default
            path: /etc/kubernetes/azure.json
            type: File
