---
imgrepo: "pathfinders.azurecr.io/nearform/"

service:
  externalPort: 80
  clusterType: ClusterIP

image: react-pwa
imageTag: 80
imagePullPolicy: Always

app:
  internalPort: 3000
  replicas: 3

ingress:
  enabled: true
  hosts:
  - hackernews.webinar.nearform.net
  annotations:
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
  - hosts:
    - hackernews.webinar.nearform.net
    secretName: dgs-tls