version: '3'
services:
  app:
    build:
      context: ../..
      dockerfile: infrastructure/docker/app.Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3080:3000
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/tmp/default.conf
      - ../frontend/build:/html:ro
    depends_on:
      - app
    ports:
      - "8080:8080"
    environment:
      - NGINX_PORT=8080
    command: /bin/bash -c "envsubst '$$NGINX_PORT' < /tmp/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
