apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
  labels:
    app: nginx-ingress-lb
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
  - port: 7000
    name: http
    targetPort: 7000
  - port: 443
    name: https
    targetPort: 443
  selector:
    k8s-app: nginx-ingress-controller
